{
    "openapi": "3.0.0",
    "info": {
        "title": "RentX Documentation",
        "description": "Car renting API",
        "version": "1.0.0"
    },
    "tags": {
        "Category": {
            "description": "list and create categories"
        },
        "Specification": {
            "description": "list and create specifications"
        },
        "User": {
            "description": "create, update and delete users"
        },
        "Car": {
            "description": "create, update and delete cars"
        },
        "Authentication": {
            "description": "authenticate users"
        }
    },
    "paths": {
        "/sessions": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Login/authentication route",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "format": "email"
                                    },
                                    "password": {
                                        "type": "string",
                                        "format": "password"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "token": {
                                            "type": "string"
                                        },
                                        "user": {
                                            "$ref": "#/definitions/User"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid user/password combination"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Creates a new user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string",
                                        "format": "email"
                                    },
                                    "password": {
                                        "type": "string",
                                        "format": "password"
                                    },
                                    "driver_license": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/User"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "E-mail already in use."
                    }
                }
            }
        },
        "/users/avatar": {
            "patch": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Updates user profile picture",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "avatar": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "Avatar updated"
                    },
                    "401": {
                        "description": "Invalid or missing JWT token"
                    },
                    "403": {
                        "description": "Unauthorized operation"
                    }
                }
            }
        },
        "/cars": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Creates a new car",
                "tags": ["Car"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Car_Request"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Car_Response"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Car already registered"
                    },
                    "401": {
                        "description": "Invalid or missing JWT token"
                    },
                    "403": {
                        "description": "Unauthorized operation"
                    }
                }
            },
            "get": {
                "summary": "Lists all available cars by brand, name or category_id",
                "tags": [
                    "Car"
                ],
                "parameters": [
                    {
                        "in": "query",
                        "name": "brand",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "query",
                        "name": "category_id",
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        }
                    },
                    {
                        "in": "query",
                        "name": "name",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/cars/upload": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": [
                    "Car"
                ],
                "summary": "Updates car images",
                "parameters": [
                    {
                        "in": "query",
                        "name": "id",
                        "description": "Car id",
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "images": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "format": "binary"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "404": {
                        "description": "Car not found"
                    }
                }
            }
        },
        "/categories": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Creates a new category",
                "description": "Creates a new category",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Category_Request"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Category_Response"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Category already exists"
                    },
                    "401": {
                        "description": "Invalid or missing JWT token"
                    },
                    "403": {
                        "description": "Unauthorized operation"
                    }
                }
            },
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "Lists all categories",
                "description": "Lists all the categories in the database",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Category_Response"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/categories/import": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Imports categories",
                "description": "Loads categories from .csv file",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Invalid or missing JWT token"
                    },
                    "403": {
                        "description": "Unauthorized operation"
                    }
                }
            }
        },
        "/specifications": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": [
                    "Specification"
                ],
                "summary": "Creates a new specification",
                "description": "Creates a new specification",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Specification"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Specification_Response"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Specification already exists"
                    },
                    "401": {
                        "description": "Invalid or missing JWT token"
                    },
                    "403": {
                        "description": "Unauthorized operation"
                    }
                }
            },
            "get": {
                "tags": [
                    "Specification"
                ],
                "summary": "Lists all specifications",
                "description": "Lists all the specifications in the database",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Specification_Response"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                },
                "avatar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "driver_license": {
                    "type": "string"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "example": {
                "id": "e8461311-19ea-4e31-be7d-2c5a58e8818a",
                "name": "user",
                "email": "user@email.com",
                "avatar": null,
                "driver_license": "xxxxxxx",
                "is_admin": false,
                "created_at": "2021-05-27T03:22:39.785Z"
            }
        },
        "Specification": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "example": {
                "name": "testSpecification",
                "description": "this is an specification"
            }
        },
        "Category_Request": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "example": {
                "name": "testCategory",
                "description": "this is an example"
            }
        },
        "Category_Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "created_at": {
                    "type": "date"
                }
            },
            "example": {
                "id": "037203e4-3924-4d86-b1a5-5e6d293069c0",
                "name": "testCategory",
                "description": "this is an example",
                "created_at": "2021-05-25T05:41:31.550Z"
            }
        },
        "Specification_Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "created_at": {
                    "type": "date"
                }
            },
            "example": {
                "id": "037203e4-3924-4d86-b1a5-5e6d293069c0",
                "name": "testSpecification",
                "description": "this is an example",
                "created_at": "2021-05-25T05:41:31.550Z"
            }
        },
        "Car_Request": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "brand": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "daily_rate": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "fine_amount": {
                    "type": "integer"
                },
                "license_plate": {
                    "type": "string",
                    "pattern": "[A-z]{3}-[0-9]{4}"
                },
                "specification_ids": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uuid"
                    }
                }
            },
            "example": {
                "name": "Strada",
                "brand": "Fiat",
                "category_id": "2da9744a-61af-4451-924b-c0bc4f58efb1",
                "daily_rate": 50,
                "description": "Fiat Strada",
                "fine_amount": 10,
                "license_plate": "ABC-1234",
                "specification_ids": [
                    "dfa9b8c8-a7bc-41ab-819e-15e48685618a"
                ]
            }
        },
        "Car_Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format":"uuid"
                },
                "name": {
                    "type": "string"
                },
                "brand": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "daily_rate": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "fine_amount": {
                    "type": "integer"
                },
                "license_plate": {
                    "type": "string",
                    "pattern": "[A-z]{3}-[0-9]{4}"
                },
                "specification_ids": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uuid"
                    }
                },
                "available": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "example": {
                "name": "Strada",
                "brand": "Fiat",
                "category_id": "2da9744a-61af-4451-924b-c0bc4f58efb1",
                "daily_rate": 50,
                "description": "Fiat Strada",
                "fine_amount": 10,
                "license_plate": "ABC-1234",
                "specification_ids": [
                    "dfa9b8c8-a7bc-41ab-819e-15e48685618a"
                ],
                "id": "91e957d0-8a52-4f68-8ef4-ae6fb884259c",
                "available": true,
                "created_at": "2021-05-30T11:46:56.674Z"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
